### ISSUE TITLE
top 2

### ISSUE THREAD

**Issue by zhemelko8** [zhemelko8/common-#3]
chose top 2 of his songs

**Comment by NataliaYur** [comment]
@zhemelko8  one moment

**Comment by IlonaSofianidi** [comment]
The people 
Glory

**Comment by zhemelko8** [comment]
but we must choose 2

**Comment by NataliaYur** [comment]
@IlonaSofianidi яй не встигла)

**Comment by NataliaYur** [comment]
@IlonaSofianidi @zhemelko8  ви бачили моє повідомлення про "Common Ground Foundation"?

**Comment by IlonaSofianidi** [comment]
@zhemelko8 @NataliaYur  можемо закрити це питання?

**Comment by zhemelko8** [comment]
@NataliaYur yessss
